#yaml
# ========================
# VOLUMES
# ========================
volumes:
  mlflow-postgres-db:
    name: mlflow-postgres-db
  mlflow-minio-data:
    name: mlflow-minio-data
  airflow-postgres-db:
    name: airflow-postgres-db
  monitoring-prometheus-data:
    name: monitoring-prometheus-data
  monitoring-grafana-data:
    name: monitoring-grafana-data

# ========================
# NETWORK
# ========================
networks:
  airflow_net:
    name: airflow_net
    driver: bridge
  mlflow_net:
    name: mlflow_net
    driver: bridge
  mlops_net:
    name: mlops_net
    driver: bridge

# ========================
# BUSINESS SERVICES
# ========================
services:
  ml-ingest-dev:
    image: ml-ingest:dev
    build:
      context: .
      dockerfile: ./docker/dev/ml/ingest/Dockerfile
    command:
      - --raw-path
      - /app/data/raw/${RAW_FILE_NAME}
      - --site
      - ${SITE}
      - --orientation
      - ${ORIENTATION}
      - --range-start
      - "${RANGE_START}"
      - --range-end
      - "${RANGE_END}"
      - --timestamp-col
      - date_et_heure_de_comptage
      - --sub-dir
      - ${SUB_DIR}
      - --interim-name
      - ${INTERIM_NAME}
    restart: "no"
    environment:
      PUSHGATEWAY_ADDR: ${PUSHGATEWAY_ADDR}
      DISABLE_METRICS_PUSH: ${DISABLE_METRICS_PUSH}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - airflow_net
      - mlops_net
    profiles: ["ml", "all"]

  ml-features-dev:
    image: ml-features:dev
    build:
      context: .
      dockerfile: ./docker/dev/ml/features/Dockerfile
    command:
      - --interim-path
      - /app/data/interim/${SUB_DIR}/${INTERIM_NAME}
      - --sub-dir
      - ${SUB_DIR}
      - --processed-name
      - ${PROCESSED_NAME}
      - --timestamp-col
      - date_et_heure_de_comptage
    restart: "no"
    environment:
      PUSHGATEWAY_ADDR: ${PUSHGATEWAY_ADDR}
      DISABLE_METRICS_PUSH: ${DISABLE_METRICS_PUSH}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - airflow_net
      - mlops_net
    profiles: ["ml", "all"]

  ml-models-dev:
    image: ml-models:dev
    build:
      context: .
      dockerfile: ./docker/dev/ml/models/Dockerfile
    command:
      - --processed-path
      - /app/data/processed/${SUB_DIR}/${PROCESSED_NAME}
      - --sub-dir
      - ${SUB_DIR}
      - --target-col
      - comptage_horaire
      - --ts-col-utc
      - date_et_heure_de_comptage_utc
      - --ts-col-local
      - date_et_heure_de_comptage_local
      - --ar
      - "${AR}"
      - --mm
      - "${MM}"
      - --roll
      - "${ROLL}"
      - --test-ratio
      - "${TEST_RATIO}"
      - --grid-iter
      - "${GRID_ITER}"
    restart: "no"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
      MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      PUSHGATEWAY_ADDR: ${PUSHGATEWAY_ADDR}
      DISABLE_METRICS_PUSH: ${DISABLE_METRICS_PUSH}
    networks:
      - mlflow_net
      - airflow_net
      - mlops_net
    profiles: ["ml", "all"]

  api-dev:
    image: api:dev
    build:
      context: .
      dockerfile: ./docker/dev/api/Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      DATA_FINAL_ROOT: ${DATA_FINAL_ROOT}
    networks:
      - airflow_net
      - mlops_net
    profiles: ["all", "api"]

# ========================
# MLFLOW SERVICES
# ========================
  mlflow-postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mlflow"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - mlflow-postgres-db:/var/lib/postgresql/data
    restart: always
    networks:
      - mlflow_net
    profiles: ["all", "mlflow"]

  mlflow-minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data
    volumes:
      - mlflow-minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: always
    networks:
      - mlflow_net
      - mlops_net
    profiles: ["all", "mlflow"]

  mlflow-mc-init:
    image: minio/mc
    depends_on:
      mlflow-minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set minio http://mlflow-minio:9000 minio minio123 &&
      mc mb -p minio/mlflow || true &&
      mc anonymous set download minio/mlflow || true &&
      touch /tmp/ok && sleep 1
      "
    networks:
      - mlflow_net
    profiles: ["all", "mlflow"]

  mlflow-server:
    image: mlflow:dev
    build:
      context: .
      dockerfile: docker/dev/mlflow/Dockerfile
    depends_on:
      mlflow-postgres:
        condition: service_healthy
      mlflow-minio:
        condition: service_healthy
      mlflow-mc-init:
        condition: service_completed_successfully
    environment:
      MLFLOW_BACKEND_STORE_URI: postgresql://mlflow:mlflow@mlflow-postgres:5432/mlflow
      MLFLOW_DEFAULT_ARTIFACT_ROOT: s3://mlflow/
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      AWS_DEFAULT_REGION: us-east-1
      MLFLOW_S3_ENDPOINT_URL: http://mlflow-minio:9000
    ports:
      - "5001:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 5s
      timeout: 5s
      retries: 30
    command:
      - server
      - --host
      - 0.0.0.0
      - --port
      - "5000"
    restart: unless-stopped
    networks:
      - mlflow_net
      - mlops_net
    profiles: ["all", "mlflow"]

# ========================
# AIRFLOW SERVICES
# ========================
  airflow-mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always
    networks:
      - airflow_net
    profiles: ["all", "airflow"]

  airflow-postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow-postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always
    networks:
      - airflow_net
    profiles: ["all", "airflow"]

  airflow-redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always
    networks:
      - airflow_net
    profiles: ["all", "airflow"]

  airflow-init:
    image: apache/airflow:2.8.1
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://:@airflow-redis:6379/0
      AIRFLOW__CORE__FERNET_KEY: "AL5jw4sTifD5GJuUXSgse1c5KXCwRFV7GFyzn7QevK8="
      _AIRFLOW_WWW_USER_USERNAME: ${AIRFLOW_WWW_USER_USERNAME}
      _AIRFLOW_WWW_USER_PASSWORD: ${AIRFLOW_WWW_USER_PASSWORD}
    user: "${AIRFLOW_UID:-50000}:0"
    depends_on:
      airflow-redis:
        condition: service_healthy
      airflow-postgres:
        condition: service_healthy
    networks:
      - airflow_net
    command: >
      bash -c "airflow db migrate &&
        (airflow users create --username ${_AIRFLOW_WWW_USER_USERNAME:-airflow} --password ${_AIRFLOW_WWW_USER_PASSWORD:-airflow} --firstname Admin --lastname User --role Admin --email admin@example.com || true) &&
        airflow variables import /opt/airflow/config/variables.json &&
        airflow connections delete api_dev || true &&
        airflow connections import /opt/airflow/config/connections.json &&
        airflow pools set sequential_counters 2 'Orchestrator: trigger child DAGs sequentially'"
    restart: "no"
    volumes:
      - ./docker/dev/airflow/:/opt/airflow/config/
    profiles: ["all", "airflow"]

  airflow-webserver:
    image: apache/airflow:2.8.1
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://:@airflow-redis:6379/0
      AIRFLOW__CORE__FERNET_KEY: "AL5jw4sTifD5GJuUXSgse1c5KXCwRFV7GFyzn7QevK8="
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
      AIRFLOW__CORE__LOAD_EXAMPLES: "true"
      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session
      AIRFLOW__SMTP__SMTP_HOST: "mailhog"
      AIRFLOW__SMTP__SMTP_PORT: 1025
      AIRFLOW__SMTP__SMTP_MAIL_FROM: "airflow@test.local"
      AIRFLOW__SMTP__SMTP_STARTTLS: "False"
      AIRFLOW__SMTP__SMTP_SSL: "False"
    user: "${AIRFLOW_UID:-1000}:0"
    group_add:
      - ${AIRFLOW_GID:-1001}
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    command: ["webserver"]
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    volumes:
      # Bind host for external exchanges
      - ./src/airflow/dags:/opt/airflow/dags
      - ./src/airflow/dags_common:/opt/airflow/dags_common
      - ./logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
      - ./src/airflow/config/bike_dag_config.json:/opt/airflow/config/bike_dag_config.json:ro
      # socket bind for container exchanges with docker desktop
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - airflow_net
      - mlops_net
    profiles: ["all", "airflow"]

  airflow-scheduler:
    image: apache/airflow:2.8.1
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://:@airflow-redis:6379/0
      AIRFLOW__CORE__FERNET_KEY: "AL5jw4sTifD5GJuUXSgse1c5KXCwRFV7GFyzn7QevK8="
      AIRFLOW__SMTP__SMTP_HOST: "mailhog"
      AIRFLOW__SMTP__SMTP_PORT: 1025
      AIRFLOW__SMTP__SMTP_MAIL_FROM: "airflow@test.local"
      AIRFLOW__SMTP__SMTP_STARTTLS: "False"
      AIRFLOW__SMTP__SMTP_SSL: "False"
      DOCKER_HOST: unix:///var/run/docker.sock
      AIRFLOW__SCHEDULER__JOB_HEARTBEAT_SEC: 5
      AIRFLOW__SCHEDULER__SCHEDULER_HEARTBEAT_SEC: 5
      AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: 5
      AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: 10
    user: "${AIRFLOW_UID:-1000}:0"
    group_add:
      - ${AIRFLOW_GID:-1001}
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    command: ["scheduler"]
    healthcheck:
      test:
        - CMD-SHELL
        - airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    volumes:
      # Bind host for external exchanges
      - ./src/airflow/dags:/opt/airflow/dags
      - ./src/airflow/dags_common:/opt/airflow/dags_common
      - ./logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
      - ./src/airflow/config/bike_dag_config.json:/opt/airflow/config/bike_dag_config.json:ro
      # socket bind for container exchanges with docker desktop
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - airflow_net
      - mlops_net
    profiles: ["all", "airflow"]

  airflow-worker:
    image: apache/airflow:2.8.1
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://:@airflow-redis:6379/0
      AIRFLOW__CORE__FERNET_KEY: "AL5jw4sTifD5GJuUXSgse1c5KXCwRFV7GFyzn7QevK8="
      DOCKER_HOST: unix:///var/run/docker.sock
      AIRFLOW__CORE__WORKER_HEARTBEAT_INTERVAL: 10
    user: "${AIRFLOW_UID:-1000}:0"
    group_add:
      - ${AIRFLOW_GID:-1001}
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    command: ["celery", "worker"]
    healthcheck:
      test:
        - CMD-SHELL
        - celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    volumes:
      # Bind host for external exchanges
      - ./src/airflow/dags:/opt/airflow/dags
      - ./src/airflow/dags_common:/opt/airflow/dags_common
      - ./logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
      - ./src/airflow/config/bike_dag_config.json:/opt/airflow/config/bike_dag_config.json:ro
      # socket bind for container exchanges with docker desktop
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - airflow_net
    profiles: ["all", "airflow"]

  airflow-flower:
    image: apache/airflow:2.8.1
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://:@airflow-redis:6379/0
      AIRFLOW__CORE__FERNET_KEY: "AL5jw4sTifD5GJuUXSgse1c5KXCwRFV7GFyzn7QevK8="
    user: "${AIRFLOW_UID:-1000}:0"
    group_add:
      - ${AIRFLOW_GID:-1001}
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    command: ["celery", "flower"]
    ports:
      - "5555:5555"
    restart: always
    networks:
      - airflow_net
    profiles: ["all", "airflow"]

# ========================
# MONITORING SERVICES
# ========================
  monitoring-prometheus:
    image: prom/prometheus:v2.54.1
    restart: unless-stopped
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=15d
    volumes:
      - ./docker/dev/prometheus:/etc/prometheus:ro
      - monitoring-prometheus-data:/prometheus
    networks:
      - mlops_net
    profiles: ["monitoring", "all"]

  monitoring-grafana:
    image: grafana/grafana:11.2.0
    restart: unless-stopped
    user: "472"  # grafana uid
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - monitoring-grafana-data:/var/lib/grafana
      - ./docker/dev/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./docker/dev/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - monitoring-prometheus
    networks:
      - mlops_net
    profiles: ["monitoring", "all"]

  monitoring-cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    restart: unless-stopped
    privileged: true
    # cAdvisor écoute en 8080 en interne : 9200:8080 exposé en host
    ports:
      - "9200:8080"
    volumes:
      # volumes dans docker desktop pour windows (ou la machine hote directement sur linux)
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      # socket bind for container exchanges with docker desktop
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mlops_net
    profiles: ["monitoring", "all"]

  monitoring-pushgateway:
    image: prom/pushgateway:v1.9.0
    ports:
      - "9091:9091"
    networks:
      - mlops_net
    profiles: ["monitoring", "all"]