groups:
  - name: container_alerts
    rules:
      - alert: ApiContainerDown
        expr: up{job="api"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "API container is down"
          description: "The API container has been unreachable for 1 minutes."

      - alert: ApiContainerRestartLoop
        expr: rate(container_last_seen{job="cadvisor", name="avr25-mle-trafic-cycliste-api-dev-1"}[1m]) > 3
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "API container restart rate too high"
          description: "The API container restarted more than 3 times in the last minute."