global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["monitoring-prometheus:9090"]

  - job_name: cadvisor
    static_configs:
      - targets: ["monitoring-cadvisor:9200"]