global:
  smtp_smarthost: 'airflow-mailhog:1025'
  smtp_from: 'alerts@mlops.local'
  smtp_require_tls: false

route:
  receiver: 'mailhog'

receivers:
  - name: 'mailhog'
    email_configs:
      - to: 'dev-team@mlops.local'