name: Workflow CI on feature branch

on:
  push: # Full Feedback on Push on feature branch
    branches-ignore:
      - main
      
jobs:
  ci-checks:
    name: 🔍 Tests & Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up UV
        uses: astral-sh/setup-uv@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: uv sync --extra dev --extra test --extra py312

      - name: Check code style with flake8
        run: |
          uv run flake8

      - name: Run tests with coverage
        run: |
          uv run pytest

      - name: Upload HTML coverage report locally
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov
          path: htmlcov